# TODO: Move this to GitHub actions once doctr supports it

language: python
sudo: false
dist: xenial
python:
  - 3.6 # Build against the lowest supported version

env:
  global:
    # Doctr deploy key for sympy/sphinx-math-dollar
    - secure: "MBgN39xVbrWbymYupYkwkRmIcwcy0nx56OH7HSeOVxByw/bhFjXBjEjm74KkIJpey35KNfIFtgrVPQ2e2Uhgh6114tRKgG2sFPXgiCTofmnUs/7xNHq5OF3XTvMRPJk3JRe65m2zbqMnhNG+uYkuABhWd14FnVC1tQmXU+U/9Nhk4brHeUas+P4FwVGTGKUcyCUHrVrjsJpaQPUcr0bVKyOYC+JyoGc23gVXf5QQXOKqzbX3zcZqbSgN4/2Jeq70/IJApD7I9jLWaO9u8abRvj4M69Y0Jw259O4MADhcKr19v6IAT8T5wSEtcN0mtyPDbuJM6qebqXB/u9hNTFttt+A/Epf3xVwDXC+Sd2196BrPGYR2xLAeu2Rh/SDz1ntlF46e0dbx+D2obIq+GHb8SUVizzfUueuGim8JbwyHBO+McCF5NPzkZzyxUhAsJWGW+4nJuBrzzSOloedfJyV0bM1QcdXY1O2WzWqCNf6Q/A2svJHplIbGnvQiqa7U2ZmfrBot3/m4dKElGHZzkQWZcvk7LMJwGUcJXuk0EX5YpSCxkwDd3s2tWlBryC40phwlxKjiHhCfzVh+ep12/Mffmu2Yv6XwXkzVCqpcWQb6YZEiJkCWQfwCDcMPaAtBb3Wfz0n2fFQUqoezYCEvB7QXxGTzmeb3u/wYUcsbrVaVnM4="

script:
  - set -e
  - pip install sphinx doctr
  - cd docs
  - make html
  - cd ..
  - doctr deploy .
